<?php
	$user_config = array(
        'vName'=>array(
            'validate'=>'1',
            'clientname'=>'userName',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'vPhone'=>array(
            'validate'=>'1',
            'clientname'=>'userPhone',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'vEmail'=>array(
            'validate'=>'1',
            'clientname'=>'userEmail',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'vUsername'=>array(
            'validate'=>'1',
            'clientname'=>'userUsername',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'vPassword'=>array(
            'validate'=>'1',
            'clientname'=>'userPassword',
            'type'=>'string',
            'html'=>'text',
            'table'=>'0'
        ),
        'iRoleId'=>array(
            'validate'=>'1',
            'clientname'=>'userRoleId',
            'type'=>'string',
            'html'=>'text',
            'table'=>'0'
        ),
        'vImage'=>array(
            'validate'=>'1',
            'clientname'=>'userImage',
            'type'=>'string',
            'html'=>'file',
            'table'=>'0'
        ),
        'dCreatedDate'=>array(
            'validate'=>'0',
            'clientname'=>'createdDate',
            'type'=>'string',
            'html'=>'',
            'table'=>'1'
        ),
        'vStatus'=>array(
            'validate'=>'1',
            'clientname'=>'userStatus',
            'type'=>'string',
            'html'=>'',
            'table'=>'0'
        )	
	) 
?>
