<?php
	$post_config = array(
        'iRescuerId'=>array(
            'validate'=>'1',
            'clientname'=>'postRescuer',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'vPostImage'=>array(
            'validate'=>'1',
            'clientname'=>'postImage',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'vComments'=>array(
            'validate'=>'0',
            'clientname'=>'postComments',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'iLikes'=>array(
            'validate'=>'0',
            'clientname'=>'postLikes',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'iViews'=>array(
            'validate'=>'0',
            'clientname'=>'postViews',
            'type'=>'string',
            'html'=>'text',
            'table'=>'1'
        ),
        'dCreatedDate'=>array(
            'validate'=>'0',
            'clientname'=>'createdDate',
            'type'=>'string',
            'html'=>'',
            'table'=>'1'
        ),
        'vStatus'=>array(
            'validate'=>'1',
            'clientname'=>'postStatus',
            'type'=>'string',
            'html'=>'',
            'table'=>'0'
        )	
	) 
?>
